### ISSUE TITLE
Turner2004 RNA parameters possibly outdated

### ISSUE THREAD

**Issue by fncnt** [jlab/fold-grammars#20]
So, this caused quite a bit of confusion for me:

It turns out that [`rna_turner2004.par`](https://github.com/ViennaRNA/ViennaRNA/blob/5d0cf4fb5e794a9859c893fad2a7f34ac64cc403/misc/rna_turner2004.par) from the `ViennaRNA` repository is different from [`rna_turner2004.par`](https://github.com/jlab/fold-grammars/blob/94050bac41e3c562bac7d00c981a6d77dede0d13/Misc/Analyses/Foldingspaces/Energyparameters/rna_turner2004.par) used here.
Apparently there were some fixes to the file in `ViennaRNA`.
Not really sure what the correct fix would be or if it should be applied here but I thought I'd point out the inconsistency.
At least in my use case, the file from `ViennaRNA` worked better in conjunction with `pKiss`.

(Looking at the history over at `ViennaRNA`, `dna_mathews2004.par` might also be affected but I haven't verified that)

**Comment by sjanssen2** [comment]
Dear @fncnt many thanks for reporting. Sounds like a lot of tracing the changes and double check the consequences of the updates - thus, don't expect an ultra fast update. We've added the files sometime in 2013 by copy&paste from the Vienna package. Let's see if we can do it again with the current version.

What do you mean with "worked better"? More realistic candidates? Faster computation?

**Comment by fncnt** [comment]
Hi @sjanssen2,
Thanks! I completely understand. It's not an actual issue per se apart from having to know that the default parameter sets of both frameworks differ slightly.
Yes, I meant more realistic candidates. I'm hesitant to give more details though, as this is probably a very anecdotal observation currently.

**Comment by RaumZeit** [comment]
Dear @sjanssen2 , @jkrue 

Could this be related to https://github.com/ViennaRNA/ViennaRNA/compare/v2.1.8...v2.1.9 as mentioned in our Changelog https://www.tbi.univie.ac.at/RNA/changelog.html#v219 ?
Up to version 2.1.9 of the ViennaRNA Package, there has been an error in the Turner Parameter files due to a wrong parser that converted the parameters from the RNAstructure Package format to our.

**Comment by sjanssen2** [comment]
Hey Ronny, this is a great starting point and has surely saved me a lot of code change tracking. Many thanks!

**Comment by sjanssen2** [comment]
Note to myself: I've based the rnalib files in gapc off Vienna RNA version 2.0.7

**Comment by sjanssen2** [comment]
Hi @RaumZeit I am working on transferring the energy fix to my repo. Unfortunately, I see some differences with the "macrostate" version of the d1 energy model. To further pinpoint the differences, it would be great if `RNAeval` would not only report the sum of `Multi loop` energy contribution but also the individual energies a multiloop is composed of, like the penalty for each stem, the penalty for opening a multiloop, ...
Is there an easy way to make `RNAeval` report these details? Maybe a hidden option, a compiler flag or a patch?
Many thanks in advance!

**Comment by sjanssen2** [comment]
update on the macrostate issue: this is due to violating Bellman's Principle in the MFE algebra: see https://github.com/jlab/fold-grammars/issues/26

**Comment by sjanssen2** [comment]
Hi @RaumZeit, in course of transferring your fix for the energy parameters, I'd like to also update my codebase such that the latest version of your source files are used: https://github.com/jlab/gapc/pull/74
The idea is to use https://github.com/jlab/gapc/blob/master/librna/rnalib.c as adapters between your and the gapc code and have all other files from ViennaRNA unchanges in directory https://github.com/jlab/gapc/tree/rnalib2.4.17/librna/ViennaRNA. This shall be compiled as a dynamic library (librna.so) such that results of gapc can link against it.

However, I am getting a seg fault when executing gapc products that link against the new version of librna.so (see comment in https://github.com/jlab/gapc/pull/74) and I don't really understand why. I figure some compile flags are wrong? If you have a spare minute, could you maybe give me a hand?

**Comment by sjanssen2** [comment]
Hi @fncnt, it took me almost a month, but the corrections from the ViennaRNA package are now also included here. Ubuntu packages have been updated as well as bioconda packages for pkiss and rnashapes. And of course for bellman's gapc, since the fix had to be applied there.
Could you please double check, if the behaviour of pkiss is now as you would expect it to be?

**Comment by fncnt** [comment]
Hi @sjanssen2, sorry that I didn't reply any sooner (missed the notification). I'm a bit busy at the moment but should find time to check mid to late next week.
Thanks for putting that much effort into it!
