### ISSUE TITLE
probing efficiency

### ISSUE THREAD

**Issue by sjanssen2** [jlab/fold-grammars#51]
I wonder why this calculation is outside the table mechanism; don't we loose efficiency here?
https://github.com/jlab/fold-grammars/blob/8cf07136e11a49b85a4d04684e3f23411e8d06c8/Extensions/probing.hh#L409-L413

I feel we should move this into the `if (!isLoaded) {` condition.

**Comment by fymue** [comment]
I think this issue can be closed considering the much improved probing efficiency/speed the PRs #53 and #54 introduced.
